ALTER PROCEDURE SP_INSERCION_EMPLEADO
	@ID_EMP INT ,
	@NOM_EMP VARCHAR ( 20 ),
	@EDAD INT ,
	@CARGO VARCHAR ( 20 ),
	@DIRECCION VARCHAR ( 50 ),
	@LOCALIDAD VARCHAR( 50 ),
	@CELULAR INT ,
	@TELEFONO INT ,
	@ID_DIS INT ,
	@FECHA_INGRESO DATETIME
AS 
BEGIN 
DECLARE @EXISTE BIT = (SELECT COUNT ( * ) FROM EMPLEADO WHERE NOM_EMP = @NOM_EMP)
	IF (@EXISTE  = 1)
	BEGIN
		DECLARE @ID_EMPLEADO int = (SELECT	TOP 1 @ID_EMP FROM EMPLEADO WHERE @NOM_EMP = NOM_EMP)
		UPDATE EMPLEADO SET 
	END
ELSE
	BEGIN
	EXEC SP_EMPLEADO
	SELECT * FROM EMPLEADO
	END
END

SELECT * FROM EMPLEADO