USE FARMACIA

--stored procedure
CREATE procedure SP_distrito AS
SET ROWCOUNT 14
SELECT DISTRITO.ID_DIS AS ID, DISTRITO.NOM_DIS
FROM DISTRITO
ORDER BY DISTRITO.ID_DIS DESC
GO


SELECT * FROM EMPLEADO
EXEC SP_EMPLEADO

CREATE PROCEDURE SP_EMPLEADO 
AS
BEGIN
	SELECT 
		E.ID_EMP AS ID,
		E.NOM_EMP AS NOMBRE,
		DE.EDAD,
		DE.CARGO,
		U.DIRECCION AS UBICACION,
		U.LOCALIDAD AS LOCALIDAD,
		U.CELULAR AS N_CELULAR,
		U.TELEFONO AS N_TELEFONO,
		DI.NOM_DIS AS DISTRITO,
		DE.INGRESO AS FECHA_INGRESO
	FROM 
		DISTRITO DI INNER JOIN (DetalleEmpledo DE INNER JOIN 
		(UBICACION U INNER JOIN EMPLEADO E ON U.ID_DIR = E.ID_DIR ) 
		ON E.ID_DE = DE.ID_DE) ON DI.ID_DIS = E.ID_DIS
END

CREATE PROCEDURE SP_INSERTAR_D_