USE FARMACIA

SELECT NAME FROM SYSOBJECTS WHERE TYPE = 'U'

--VITAS
GO
ALTER VIEW VW_PRODUCTO
(	ID,
	NOMBRE,
	DESCRICION,
	PRESENTADOR,
	PRE_VENTAS,
	STOCK,
	PRE_COMPRAS,
	FECHA_VENC)	
AS
	SELECT
		P.ID_PRO,
		P.NOM_PRO,
		C.NOM_DES,
		PR.NOM_PRE,
		DP.PRE_VENTAS,
		DP.STOCK,
		DP.PRE_COMPRAS,
		DP.FECHA_VENC	
	FROM 
		PRESENTACION PR INNER JOIN (CATEGORIA C INNER JOIN 
		(DETALLE_PRODUCTO DP INNER JOIN PRODUCTO P ON DP.ID_DP = P.ID_DP) 
		ON C.ID_CATE =  P.ID_CATE) ON P.ID_PRES = PR.ID_PRE  
GO		
--============

CREATE VIEW VW_USUARIOS
(	ID,
	NOMBRE,
	CONTRASEÑA,
	ACTIVO,
	"NIVEL DE USUARIO",
	"ID DE EMPLEADO",
	"NOMBRE DEL EMPLEADO"
	)
AS
	SELECT 
		U.ID_DU,
		U.NOM_USU,
		U.CONTRASEÑA,
		DU.ACTIVO,
		DU.NIVEL_USUARIO,
		E.ID_DE,
		E.NOM_EMP
	FROM 
		EMPLEADO E INNER JOIN ( DETALLE_USUARIO DU INNER JOIN USUARIO U ON DU.ID_DU = U.ID_DU )ON U.ID_EMP = E.ID_EMP;
GO
--============

CREATE VIEW VW_PROVEEDOR
	(ID,
	PROVEEDOR,
	DISTRITO,
	DIRECCION,
	LOCALIDAD,
	CELULAR,
	TELEFONO
	)
AS
	SELECT 
		P.ID_PROV,
		P.NOM_PROV,
		d.NOM_DIS,
		u.DIRECCION,
		U.LOCALIDAD,
		U.CELULAR,
		U.TELEFONO
FROM 
		UBICACION U INNER JOIN ( DISTRITO D INNER JOIN PROVEEDOR P ON P.ID_DISTRITO = D.ID_DIS) 
		ON P.ID_DIR = U.ID_DIR;
GO

ALTER VIEW VW_CLIENTES
	(ID,
	"NOMBRE DEL CLIENTE",
	SEXO,
	DIRECCION,
	LOCALIDAD,
	CELULAR,
	TELEFONO
	)
AS
	SELECT 
		C.ID_DIR,
		C.NOM_CLI,
		C.SEXO,
		U.DIRECCION,
		U.LOCALIDAD,
		U.CELULAR,
		U.TELEFONO
	FROM 
		CLIENTES C INNER JOIN UBICACION U ON C.ID_DIR = U.ID_DIR
GO